### PR TITLE
Prevent overwriting .htaccess file

### PR DESCRIPTION
**Pull request by evertalbers**
Inspred by https://discuss.bolt.cm/d/123-updating-using-ssh-overwriting-custom-htaccess

### CODE REVIEW

**Comment by SahAssar** [comment]
Might just be my CDO acting up, but could you wrap the text at 80 chars?

**Comment by evertalbers** [comment]
If only I knew how to do that with the GitHub web client…

Sorry for that.

**Comment by SahAssar** [comment]
@evertalbers: Here, copy-paste this:
```
<p class="note"><strong>Note:</strong> If you have made edits to your .htaccess
file, make a backup of this file on your own computer (e.g. renamed
clientname_v01.htaccess so it becomes visible) or make sure that it does not
get overwritten by changing the permissions.</p>
```

**Comment by evertalbers** [comment]
Just made a new pull request with that. 
Probably not the way to go, but I hope it works.

**Comment by GawainLynch** [comment]
Line lengths we can fix on merge, but renaming `.htaccess` to a "visible" name is a minor security problem, as that then becomes publicly accessible and potentially disclosing server configuration information.

I might make an edit after merge, prior to pushing to the server.

**Comment by evertalbers** [comment]
Thanks!

**Pull request merged**
