### PR TITLE
change composer create-project to composer install command

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
This makes much more sense than before.

### CODE REVIEW

**Comment by GawainLynch** [comment]
That isn't correct. We need the events to run.

**Comment by PhillippOhlandt** [comment]
But `composer create-project` isn't correct too. 

Then we should move 
```
"Bolt\\Composer\\ScriptHandler::installThemesAndFiles",
"nut extensions:setup"
```

to `post-install-cmd` and we could remove `Bolt\\Composer\\ScriptHandler::configureProject` completely.

Then the required still runs after you ran `composer install`.

**Comment by PhillippOhlandt** [comment]
Note: I mean just the event handlers in the `composer.json` in the docs here.

**Comment by PhillippOhlandt** [comment]
Other thing. I would prefer to remove the whole "Create all config files manually and run composer *" section anyway. 

`composer create-project bolt/composer-install` is the preferred way and the manual method means just trouble.

**Comment by GawainLynch** [comment]
:+`

**Pull request merged**
