### PR TITLE
Describe auto-scaling for thumbs

### PR DESCRIPTION
**Pull request by GDmac**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Looks good to me! 👍  

@GawainLynch Can you merge this into `release/3.0` and cascade up?

**Comment by GawainLynch** [comment]
@bobdenotter I am probably missing something … but isn't this a part of "Thumbnail Aliases", that were added in 3.2?

**Comment by GDmac** [comment]
ah @GawainLynch i just clicked edit on bolt-docs page which brought me to the file and commit merge pr it. @bobdenotter  i'll try if i can cascade it up via github

**Comment by GDmac** [comment]
BTW @GawainLynch, autoscaling was a thumbs feature from the beginning, it just never was documented :-)

**Comment by GDmac** [comment]
pull request made to release/3.0 branch i have no idea how to cascade it up the tree.

**Comment by GawainLynch** [comment]
It's OK, I could have moved the branch, and the cascade is just the merging of the release branches also handled here

**Pull request closed without merging**
