### PR TITLE
Removed events that aren't implemented yet

### PR DESCRIPTION
**Pull request by Maelstromeous**
`\Bolt\Events\StorageEvents::PRE_INSERT`
`\Bolt\Events\StorageEvents::POST_INSERT`

### CODE REVIEW

**Comment by GawainLynch** [comment]
Flagging… this appears in 3.0+ so will need redirection on merge

**Comment by GawainLynch** [comment]
c.f.[3.0 events](https://github.com/bolt/docs/blob/release/3.0/docs/extensions/intermediate/events.md)

**Comment by bobdenotter** [comment]
Pinging @GawainLynch: Is this GTG, or does it need tweaking?

**Comment by GawainLynch** [comment]
Needs to be moved down to 3.0 … and :koala: travel :laughing:

**Comment by GawainLynch** [comment]
Merged into `release/3.0` via e560e1a0197521db1610173d352feaa0e7d9d434

Thanks again, @Maelstromeous

**Pull request closed without merging**
