### PR TITLE
add new contenttype and recordslug in the arg explanation part

### PR DESCRIPTION
**Pull request by dadaxr**

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Doesn't that work before Bolt 3.1? Or just overseen the branch name?

**Comment by GawainLynch** [comment]
> Doesn't that work before Bolt 3.1? 

Yeah, already flagged it to check and move if required mate … just getting lower hanging pineapples taken care of first :wink:

**Comment by dadaxr** [comment]
Mmm I guess I overseen the branch name :) I just clicked on the 

> Spotted a typo, or have something to add? Edit this page on Github.

at the bottom of the doc page.

& when looking at bolt 2.2 routing doc ... those params were already present so I guess yeah you can move it ? :p

**Comment by GawainLynch** [comment]
Merged into `release/3.0` via e054a5a1d75e222958653ed0a1f13aaa2b1297ac

**Pull request closed without merging**
