### PR TITLE
Added Translations documentation.

### PR DESCRIPTION
**Pull request by Raistlfiren**
This is a real basic overview of how to use Translations with Extensions. Simple but sweet... 

Closes https://github.com/bolt/docs/issues/493

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Looks good structure wise but I don't think we need to mention the Bolt version because it's only in the 3.1+ docs.

**Comment by Raistlfiren** [comment]
Well, the translation functionality wasn't included until 3.1 so I would hate for someone to overlook that minor fact.

**Comment by PhillippOhlandt** [comment]
Yeah but for that reason, we have versioned documentation.

**Comment by Raistlfiren** [comment]
I just feel like there will be a lot of headaches wondering "why is this not working??". :) OH well.

**Comment by PhillippOhlandt** [comment]
Yeah but that's not our problem. We also have some additional pages for the storage system on the 3.1 or 3.2 branch.

**Comment by GawainLynch** [comment]
:+1:

**Pull request merged**
