### PR TITLE
Add a separate link prefix so assets and hrefs can use different variables

### PR DESCRIPTION
**Pull request by rossriley**

### CODE REVIEW

**Comment by GawainLynch** [comment]
I have a merge conflict resolution half done locally… WRT `src/Command/BuildDocumentation.php` I presume we don't need the changes from #295 for that file @bobdenotter ?

**Comment by bobdenotter** [comment]
I don't think this is needed. It'll look quite different soon: https://github.com/bolt/docs/tree/refactor-codebase

**Comment by GawainLynch** [comment]
> I don't think this is needed. 

This PR you mean?

**Comment by bobdenotter** [comment]
Yes.. The changes in index.php are not relevant after the refactor. And i've simplified the recursion in my version of the code, as pointed out by Ross. See: https://github.com/bolt/docs/blob/master/src/Command/BuildDocumentation.php#L59 

(which I accidentally pushed to master instead of to my branch, oops)

**Comment by GawainLynch** [comment]
OK then… Second BPFL act for the day…

**Pull request closed without merging**
