### PR TITLE
Added a useful ckeditor option

### PR DESCRIPTION
**Pull request by nealmarques**
I thought people might find it useful to be able to remove some of the buttons from ckeditor.  I listed all the bolt default ones.

### CODE REVIEW

**Comment by SahAssar** [comment]
If possible I'd like for this to use the "folded style" or "literal style" of yaml (see when CTRL-f "fold" here: http://symfony.com/doc/current/components/yaml/yaml_format.html) so that we don't get the excessive line-length and can easier list the options. It'd also allow for nice git diffs 😄

**Comment by nealmarques** [comment]
Thing is though, white space is actually important inside those quotes.  You add a space before after any comma there, and it the button will appear... if I'm even following what you are saying.

**Comment by SahAssar** [comment]
Right, that's what I meant by "if possible". If it's not then don't, I just wanted to check if it is 😄 Perhaps we can have the comment on the preceding line though? Something like

```
# The next line controls which of the bolt default formatting buttons should be shown
```

**Comment by bobdenotter** [comment]
Merged into 3.0, in 1660d3cb183dc32f8b87d7a3a62a75ab4c34b76c. 

Thanks, @nealmarques 

I'll ninja-edit the comment, as @SahAssar suggested. 👍

**Pull request closed without merging**
