### PR TITLE
add note for the extended extension starter repo

### PR DESCRIPTION
**Pull request by PhillippOhlandt**
Your decision if you want to merge now or in a few days when there is real content in the extended extension starter repo.

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Maybe you can merge it in now because the extended extension starter has the routes now and will be updated over the weekend. 

And don't forget to register the extension-starter-extended package at packagist =)

**Comment by GawainLynch** [comment]
On to it!

**Comment by GawainLynch** [comment]
Done!

**Comment by PhillippOhlandt** [comment]
Awesome!

**Pull request merged**
