### PR TITLE
Updating README with minor additions.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Looks good to me. Ping @SahAssar for second check. If this gets merged, you should also do this against the `release/2.2` branch so it gets merged down and appears on the default branch `release/3.1`.

**Comment by SahAssar** [comment]
Why was this and #499 against `site`? Am I missing something here?

**Comment by PhillippOhlandt** [comment]
This is because we have the same readme across all branches and the other one changed the default fallback in the source.

**Comment by SahAssar** [comment]
Edited my comment, LGTM 👍

**Comment by PhillippOhlandt** [comment]
Then I will merge this in and @bobdenotter needs to do a second PR for the `release/2.2` branch.

**Pull request merged**
