### PR TITLE
Update intro.md

### PR DESCRIPTION
**Pull request by evertalbers**
Hope the English is clear. Anyway, I was very glad when I found this trick.

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Ah, cool. Btw, just a notice for @GawainLynch, this should go into 3.0.

**Comment by GawainLynch** [comment]
Awesomesauce @evertalbers … Thanks for following up on this mate!

**Comment by bobdenotter** [comment]
One sec before merging.. Tabs need to be replaced with spaces. :-)

screen shot 2016-10-21 at 11 18 17

**Comment by GawainLynch** [comment]
@bobdenotter I was planing on catching that on merge

**Comment by bobdenotter** [comment]
Evert mentioned on slack that he's on it already.

**Comment by bobdenotter** [comment]
Looks good to me! Thanks, @evertalbers 👍 

@GawainLynch Will you handle merging?

**Comment by GawainLynch** [comment]
Yeah, was about to push a fixed and rebased merge when you called out anyway … 2nd time lucky :wink:

**Comment by GawainLynch** [comment]
Merged into `release/3.0` via a75160d123b66d113bbcf6b949d6d892fd36ff3d

**Pull request closed without merging**
