### PR TITLE
Fix "quick links"

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by CarsonF** [comment]
I'm not understanding the change for `current` (slug) twig variable. I'm pretty sure that will break things

**Comment by bobdenotter** [comment]
@CarsonF Before I changed it, and i did `{{ current }}` in the index.twig, It came out as `/local//local/foo/bar`.

**Comment by CarsonF** [comment]
And now it comes out as `/local/foo/bar`?

**Comment by bobdenotter** [comment]
Yes. At least on my setup it does. If you think it breaks, I'll do more monkey testing tomorrow. 🐵

**Comment by CarsonF** [comment]
No maybe it changed with an update last night. I'll double check later tonight. I'll merge if we are good (which I think we are)

**Comment by GawainLynch** [comment]
Let's do this!

**Pull request merged**
