### PR TITLE
Update custom-bootstrapping.md

### PR DESCRIPTION
**Pull request by hoobtron**
wont execute php code without it.

btw. referring to this: I'm stuck at the end of this doc... maybe someone can help me with this please?:
https://discuss.bolt.cm/d/402-multi-subsite-setup-menu-routing-problem/4

### CODE REVIEW

**Comment by GawainLynch** [comment]
Right, but that one is somewhat (reasonably) assumed though.

**Comment by hoobtron** [comment]
yup, but took me some minutes... sorry, I'm a noob ;)

**Comment by PhillippOhlandt** [comment]
That pages needs a rewrite anyway. Look at our tracker at #483

**Comment by hoobtron** [comment]
um ok, so I guess I'm subscribing #483

**Comment by GawainLynch** [comment]
@PhillippOhlandt I'm going to close this, cleaning up for 3.2 release … 

Let's have a chat soon about the best way to display this when we gt ready to merge the next round of work on 483.

**Comment by PhillippOhlandt** [comment]
There is already a PR from ross which needs a review from carson.

**Comment by GawainLynch** [comment]
Yeah, we were discussing it this morning … I am actually looking into his requested changes right now (for the last hour or two) :smile:

**Pull request closed without merging**
