### PR TITLE
Remove duplicate content

### PR DESCRIPTION
**Pull request by Ichag**
The deleted content seams to be the same as the remaining content about Permissions.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Well, if that isn't a copy/pasta boo-boo, I don't know what :laughing:  

Nice work, and thank you :+1:

**Comment by GawainLynch** [comment]
Merged into `release/3.0` via 740066c591ef11aed3da91d79884ebe918f85032

**Comment by PhillippOhlandt** [comment]
IIRC that removed block was PRed from @bobdenotter last week.

**Comment by GawainLynch** [comment]
Ah … it will be OK either way, git + :princess: can handle it :smile:

**Comment by GawainLynch** [comment]
I'll cascade the branches soon too, just have a bit to cover off first

**Pull request closed without merging**
