### PR TITLE
Theme.yml info corrected

### PR DESCRIPTION
**Pull request by hansgrinwis**
Deleted 'template selection' part, as it has a separate page. The info here was not totally correct anyway.
Changed 'theme.yml' because theme.yml has priority over 'config.yml'.

### CODE REVIEW

**Comment by bobdenotter** [comment]
The typos and removed duplicates look good, but why did you remove the section about `foo.twig`. That still works, right?

**Comment by hansgrinwis** [comment]
I deleted that because it is not complete info. The complete info is available in the page before this one (the one on template selection).

However, you made me thinking: if you start with no template defined anywhere, Bolt will try to find `foo.twig`, and if `foo.twig` does exist, the only way to override that is via the Contenttype (either by `listing_template` or a `templateselect` field). It confused me that the template selection from (`theme.yml` or) `config.yml` was not mentioned here, but that only applies once`foo.twig` does not exist.

I will undelete that part, when I have access to a decent workstation. (Currently typing on my phone.)

Thanks.

**Comment by bobdenotter** [comment]
Ok, sounds good. When you've updated the PR, i'll take another look! 👍

**Comment by hansgrinwis** [comment]
This is better, I think...

**Review by bobdenotter — APPROVED** [review]
Looks good to me now! Thanks, @hansgrinwis 👍

**Pull request merged**
