### PR TITLE
Setting the default to correct version 3.2.

### PR DESCRIPTION
**Pull request by bobdenotter**
[ Insert beaker.gif ]

### CODE REVIEW

**Comment by GawainLynch** [comment]
@CarsonF any reason this is hardcoded?

**Comment by bobdenotter** [comment]
It picks it up from `app/config.yml`, but there should be _some_ default, right?

**Comment by GawainLynch** [comment]
Yeah, just worries me that we'd be updating this for every minor/major version change

**Comment by GawainLynch** [comment]
I'll send in, and we can come up with better ideas later … 

Just a note though … as we got our hand forced on the default branch, and it is currently `master`, people won't have `release/3.2` available locally without building worktrees … add to that, `release/3.2` is almost always going to be the wrong branch to work on … CBF Factor 11 :hushed: :see_no_evil:

**Comment by bobdenotter** [comment]
The README [here](https://github.com/bolt/docs) details the set up. Even I could figure it out from that. I think it's not too much to expect from people who want to work on the docs, to read that.

**Comment by GawainLynch** [comment]
> I think it's not too much to expect from people who want to work on the docs, to read that.

Not too much at all … just history has proven otherwise. Several times :wink:

**Comment by CarsonF** [comment]
We could change the default to use the first version found? Or maybe the highest version found?

**Comment by GawainLynch** [comment]
Meh, too much work :laughing:

**Pull request merged**
