### PR TITLE
V3 installs

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by CarsonF** [comment]
For composer create-project installs:
* can we make a note about permissions already being applied?
* can we note a no-interaction option (and optional env vars for customization)?

```
env BOLT_DIR_MODE=0755 BOLT_WEB_DIR=mypublic \
  composer create-project bolt/composer-install:^3.0 --prefer-dist --no-interaction
```
valid env vars:
```
BOLT_DIR_MODE
BOLT_WEB_DIR
BOLT_THEMES_DIR
BOLT_FILES_DIR
BOLT_CONFIG_DIR
BOLT_DATABASE_DIR
BOLT_CACHE_DIR
```

**Comment by GawainLynch** [comment]
Sure… I pushed this to PR to get feedback from @bobdenotter for things like this, so much appreciated!

**Comment by bobdenotter** [comment]
Looks good to me!

**Comment by GawainLynch** [comment]
@CarsonF I am going to address your comments in a follow up… just want to get this "flowing" right now… the whole "more eyes" thing :smiley:

**Pull request merged**
