### PR TITLE
Add small 'working with editor-provided' links section

### PR DESCRIPTION
**Pull request by bobdenotter**
Also goes with bolt/bolt#6614.

### CODE REVIEW

**Comment by GawainLynch** [comment]
Any reason to target 3.3? This works for 3.0+

**Comment by bobdenotter** [comment]
We added the "templating/linking-in-templates" pages in 3.3 only. :-)

**Comment by GawainLynch** [comment]
So … https://github.com/bolt/docs/blob/release/3.0/docs/templating/linking-in-templates.md

**Comment by bobdenotter** [comment]
I see.. Derp.. Guess i was confused. It can just go into `release/3.0` then.

**Pull request merged**
