### PR TITLE
[4.0] Core path changes

### PR DESCRIPTION
**Pull request by GawainLynch**
Accompanies https://github.com/bolt/bolt/pull/6982

This also has cherry-picks of a bunch of pending PRs. I'll rebase once they're merged in and the branches are themselves merged.

### CODE REVIEW

**Comment by bobdenotter** [comment]
If we delete `multi-site-setup.md`, should we also delete the two other deprecated ones: `building-multilingual-websites` and `boilerplate-for-building-multilingual-websites`?

**Comment by GawainLynch** [comment]
I was hoping someone was going to suggest that! WFM :+1:

**Comment by bobdenotter** [comment]
Goes in tandem with https://github.com/bolt/bolt/pull/682

**Comment by GawainLynch** [comment]
> Goes in tandem with bolt/bolt#682

How to create an admin extension?

**Comment by bobdenotter** [comment]
I meant to put `6982` there.. Somewhere i must've lost a `9`.

**Comment by GawainLynch** [comment]
Oh right, you mean what is in the OP? I thought that might have been it, but Friday afternoon and I was scratching my head.

**Pull request merged**
