### PR TITLE
Update Magnific Popup explanation

### PR DESCRIPTION
**Pull request by anketwokings**
Explain how to show the correct caption in Magnific Popup

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Wrong branch. Can you resubmit for the release/3.0 branch?

**Comment by PhillippOhlandt** [comment]
Nah

**Comment by anketwokings** [comment]
I just clicked the editlink on https://docs.bolt.cm/3.1/templating/templatetags, and submitted the pull requested. Don't really know why it should go to 3.0?

**Comment by PhillippOhlandt** [comment]
Because this seems to be the same for bolt 3.0.

**Comment by GawainLynch** [comment]
@PhillippOhlandt (and @anketwokings) … I'll handle the branches.

**Comment by GawainLynch** [comment]
Merged into `release/3.0` via 04c40595c23894e9b5a986f99e70d5586d2113d1 and will arrive in a later branch near you shortly.

Thank you all :+1:

**Pull request closed without merging**
