### PR TITLE
Fixing commands in docs for create-project extension.

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Hmm, then we have to tag every update on the starter extensions. We could leave the extended one on master because it's not switched to Bolt 3 synthax yet.

**Comment by GawainLynch** [comment]
It's being updated, I caught it already :wink:

**Comment by bobdenotter** [comment]
Updated :-)

**Comment by PhillippOhlandt** [comment]
#yolo :P

**Comment by PhillippOhlandt** [comment]
Looks good to me.

**Comment by GawainLynch** [comment]
> Looks good to me.

Apart from using `~` instead of the Composer suggested/documented `^` yeah :wink:

**Comment by PhillippOhlandt** [comment]
>Looks good to me.
Apart from using ~ instead of the Composer suggested/documented ^ yeah :wink:

Haha, I am not fully awake yet :P

**Pull request merged**
