### PR TITLE
Better explanation of 'show in menu' option

### PR DESCRIPTION
**Pull request by anketwokings**
ohai!

### CODE REVIEW

**Comment by GawainLynch** [comment]
Ha! That's what that setting is for … thanks, now I know because of this :smile:

**Comment by anketwokings** [comment]
You were not the only one. :) Lodewijk and Xiao as well.

**Comment by PhillippOhlandt** [comment]
You edited ContentType to the wrong version xD

**Comment by GawainLynch** [comment]
Where … they are all old style in that diff.

**Comment by anketwokings** [comment]
I'll leave you two guys arguing over the versioning, and play dumb blonde here. :)

**Comment by GawainLynch** [comment]
@anketwokings yeah, it's internal and could have been expressed better :wink:

**Comment by PhillippOhlandt** [comment]
Yeah we should communicate somewhere that we use ContentType and not Contenttype or contenttype.

**Comment by GawainLynch** [comment]
> Yeah we should communicate somewhere that we use ContentType and not Contenttype or contenttype.

`public static function capital_T_dangit()`

Yeah, and for (most) people who don't know what the standards are, lets not laugh at them, either point them to a "guide page", or flag it

> @GawainLynch can you catch the "T" on merge if you haven't seen it already.

**Comment by anketwokings** [comment]
Oh, that! I saw that in the docs, but not in the cheatsheet, so adjusted it to the latter. 
So basically, the whole cheatsheet needs fixing then?

**Comment by GawainLynch** [comment]
@anketwokings Yeah, almost certainly … all PRs welcome too

**Comment by PhillippOhlandt** [comment]
@GawainLynch I didn't laugh at Anke, I just noted that she changed the correct one to the wrong one.

Anyways, I could also look over the docs and fix some stuff.

**Comment by anketwokings** [comment]
https://github.com/bolt/docs/pull/503 
@PhillippOhlandt there you go!

**Pull request merged**
