### PR TITLE
Assign return value from app.config.set() to a variable so it's not output to the browser

### PR DESCRIPTION
**Pull request by GawainLynch**
Fixes https://github.com/bolt/bolt/issues/3414

### CODE REVIEW

**Comment by CarsonF** [comment]
Wait why was `set ret =` included?

**Comment by GawainLynch** [comment]
> Wait why was `set ret =` included?

It b0rks… I gave up caring past that.

**Comment by CarsonF** [comment]
I knew it! I didn't think it was that easy. Oh well this is a workaround anyways

**Comment by GawainLynch** [comment]
At least I am testing my changes… to docs… 'cause… yeah…

**Pull request merged**
