### PR TITLE
Fix double copy-paste links. 

### PR DESCRIPTION
**Pull request by bobdenotter**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Like this: 

screenshot 2016-04-28 19 53 05

**Comment by GawainLynch** [comment]
@rarila is going to kill me… but the green button… the green button!

**Comment by bobdenotter** [comment]
Why would rarila be against this?

**Comment by GawainLynch** [comment]
He wouldn't… I was tagging him humorously… apparently I failed :sob:

**Comment by bobdenotter** [comment]
haha, I though i made some javascript no-no! 😂

**Comment by GawainLynch** [comment]
Haha… OK, so there are two things I fail at miserably… JavaScript, and JavaScript… I am the last person to take seriously on that one :laughing:

**Pull request merged**
