### PR TITLE
Add note about internal use of double underscore prefix

### PR DESCRIPTION
**Pull request by SahAssar**
See discussion in bolt/bolt#7012

### CODE REVIEW

**Comment by GawainLynch** [comment]
> Shouldn't we just include this in the docs from 3.0 and up, though?

I was just contemplating this over coffee, and I can grab the branch jump — easy as pie — when I am back on Monday.

**Comment by bobdenotter** [comment]
I can do that too, no problem.. Just asking if we agree on that. :-)

**Comment by GawainLynch** [comment]
Well, `__nodes` has been there since `2.something` so 3.0 is the best :dart: IMHO

**Comment by SahAssar** [comment]
Yep, going from 3.0 sounds good to me... I'm not at a computer to do the rebase right now though

**Pull request merged**
