### PR TITLE
Updated Custom Bootstrapping Guide

### PR DESCRIPTION
**Pull request by rossriley**
updated bootstrapping guide to reflect new modifications in project structure

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Why doesn't this point to `release/3.0`?

**Comment by rossriley** [comment]
Most of it is specific to https://github.com/bolt/bolt/pull/5748 which will target 3.2

**Comment by PhillippOhlandt** [comment]
And whats with 3.0 and 3.1? I think we need something for that too.

**Comment by GawainLynch** [comment]
@rossriley the difference being the hidden fail versus non-hidden, isn't it? In which case we can probably merge to 3.0 an updated version of this PR, and then on  cascade update the 3.2+ branch(es)

**Comment by GawainLynch** [comment]
Covered in #530

**Pull request closed without merging**
