### PR TITLE
Add note about local assets to fix #4047

### PR DESCRIPTION
**Pull request by SahAssar**
Fixes bolt/bolt#4047

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Could you define the path structure too? I saw many people using wrong paths and wondering why it still doesn't work.

**Comment by SahAssar** [comment]
@PhillippOhlandt fixed. And I discovered that github autocloses PR's without any commits in them :smile:

**Comment by PhillippOhlandt** [comment]
@SahAssar i think thats a wrong path. its `/public/extensions/local/{yourname}/{extensionname}/js/demo.js`

Note the js (and also css) subfolders.

**Comment by SahAssar** [comment]
Looks like I'm one of the "many people" you mentioned :wink: Should be fixed now!

**Comment by PhillippOhlandt** [comment]
that looks good :)

**Pull request merged**
