### PR TITLE
V3 extensions storage

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by PhillippOhlandt** [comment]
Do we have docs explaining (when) to write own entities and repositories?

**Comment by GawainLynch** [comment]
> Do we have docs explaining (when) to write own entities and repositories?

You mean the first link in the repositories file in this PR?

**Comment by PhillippOhlandt** [comment]
Yeah it explains how to map a custom entity and repository but I don't know why I should write my own and how to do that.

**Comment by GawainLynch** [comment]
Then the storage docs need expansion…

**Comment by PhillippOhlandt** [comment]
Yeah but no rush. I guess you need an own repo and entity when you add a database table that doesn't belong to a contenttype? So I think it will work when you show how to make the GumTree entity and repo.

**Comment by GawainLynch** [comment]
Documenting the making of the Entity and Repository classes belongs in the storage docs, otherwise we end up with them documented in several places… and things can get out of sync really fast.

**Comment by PhillippOhlandt** [comment]
Then do it master koala :)

**Comment by bobdenotter** [comment]
:+1:

**Comment by bobdenotter** [comment]
Apparently @jkazimir knows what the issue is, here! :tada:

**Pull request merged**
