### PR TITLE
Replacing hardcoded version numbers with '%%VERSION%%'.

### PR DESCRIPTION
**Pull request by bobdenotter**
Will be followed up by a small PR for `site`.

### CODE REVIEW

**Comment by bobdenotter** [comment]
Ugh.

**Comment by bobdenotter** [comment]
Should be GTG now. Probably best to use the "Squash and merge" option, because I made a mess. :-)

**Comment by GawainLynch** [comment]
Rebased, at 3.0, and will re-add in the 3.2 specific part of the last commit on merge.

**Comment by GawainLynch** [comment]
Second stage of the PR merged via 900eb5c9b496e7cb75495d3c767895cb3aa6f569

**Pull request merged**
