### PR TITLE
Add JSON to list of denied file types for Nginx

### PR DESCRIPTION
**Pull request by GawainLynch**

### CODE REVIEW

**Comment by bobdenotter** [comment]
Should we block JSON by default? We often make sites with maps, where the data is pulled in as JSON. For a recent example, see: http://vuurwerkoverlast.nl/page/kaart, where we pull in http://vuurwerkoverlast.nl/files/static/meldingen.json

**Comment by GawainLynch** [comment]
Well… [you tell me](http://vuurwerkoverlast.nl/extensions/composer.json) :wink:

**Comment by GawainLynch** [comment]
But that doesn't mean that people can't turn it on as needed…

**Comment by bobdenotter** [comment]
right.. Well, changing it in the default `.htaccess` like this would mean breakage for a lot of people, without a clear indication of what/how/why.. 

For example, if it's merged into Bolt 2.2.15, sites like itgwo.nl and 200jaarstatengeneraal.nl would just stop working. 

I'd rather we specifically blacklist `package.json`, `composer.json` and `bower.json`.

**Comment by GawainLynch** [comment]
Do they run Nginx?

**Comment by GawainLynch** [comment]
Oh I see… comments are not matching PRs… Yeah, I have no problem updating https://github.com/bolt/bolt/pull/4610 to limit that. But this PR is only what is documented and that won't break existing sites.

**Comment by bobdenotter** [comment]
Ah, yes. I lumped them together in my head. :-)

I think the "default nginx config" as documented should match the .htaccess one functionality-wise. So, imho it'd be best to update this one accordingly as well.

**Comment by GawainLynch** [comment]
Updated and tested locally.

**Comment by bobdenotter** [comment]
Looks good to me!

**Comment by GawainLynch** [comment]
Teamwork FTW!

**Pull request merged**
